# syntax=docker/dockerfile:1.4

FROM ghcr.io/jimpick/lotus-fvm-localnet-lite@sha256:93c9c27d00dbd0e4e397ae9700d8dfc3bc8ee9aa9c60201423a49602dead8145

USER root

RUN apt-get update
RUN apt install -y python3

WORKDIR /home/ubuntu

USER ubuntu

