# syntax=docker/dockerfile:1.4

FROM ghcr.io/jimpick/lotus-fvm-localnet-lite@sha256:8802ad6bfe06aca953845732193a84e60fca7564e646a6480c22fa461845cb21

USER root

RUN apt-get update
RUN apt install -y python3

WORKDIR /home/ubuntu

USER ubuntu

