# syntax=docker/dockerfile:1.4

# See: https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md

FROM ghcr.io/jimpick/lotus-fvm-localnet-ubuntu-dev@sha256:c172c01f49c9818bf6ffd96a770961dbf57fd4d9da2e8c4f5fecd185c74b3107

# https://lotus.filecoin.io/developers/local-network/

ENV LOTUS_PATH="/home/ubuntu/.lotus-local-net"
ENV LOTUS_MINER_PATH="/home/ubuntu/.lotus-miner-local-net"
ENV LOTUS_SKIP_GENESIS_CHECK=_yes_
ENV CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
ENV CGO_CFLAGS="-D__BLST_PORTABLE__"

# Copy lotus and go-jsonrpc
WORKDIR /home/ubuntu
COPY --chown=ubuntu:ubuntu .git .git
COPY --chown=ubuntu:ubuntu lotus lotus
COPY --chown=ubuntu:ubuntu go-jsonrpc go-jsonrpc
COPY --chown=ubuntu:ubuntu patch-lotus.sh patch-lotus.sh

RUN ./patch-lotus.sh

WORKDIR /home/ubuntu/lotus

# Patch go.mod to use go-jsonrpc with extra API request logging

RUN echo 'replace	github.com/filecoin-project/go-jsonrpc  => ../go-jsonrpc' >> go.mod

# Build Lotus

RUN make clean 2k
RUN make lotus-shed

# Fetch params

RUN ./lotus fetch-params 2048

# Node config file

RUN mkdir -p $LOTUS_PATH
RUN ./lotus config default > $LOTUS_PATH/config.toml
RUN sed -i 's,#EnableEthRPC = false,EnableEthRPC = true,' $LOTUS_PATH/config.toml
## FIXME: Set EnableEthRPC to true
