# syntax=docker/dockerfile:1.4

FROM ghcr.io/jimpick/lotus-fvm-localnet-lite@sha256:188b0f4f5d44aa1aab980db1be4940b14702071155d0dffb887ae8892efd62ae

USER root

RUN apt-get update
RUN apt install -y python3

WORKDIR /home/ubuntu

USER ubuntu

