# syntax=docker/dockerfile:1.4

# See: https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md

FROM ghcr.io/jimpick/lotus-fvm-localnet-ubuntu-dev@sha256:996e52d528d856b83b0475e063f884cfa61c7d06791b727256952cf11231b100

# https://lotus.filecoin.io/developers/local-network/

ENV LOTUS_PATH="~/.lotus-local-net"
ENV LOTUS_MINER_PATH="~/.lotus-miner-local-net"
ENV LOTUS_SKIP_GENESIS_CHECK=_yes_
ENV CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
ENV CGO_CFLAGS="-D__BLST_PORTABLE__"

# Patch go.mod to use go-jsonrpc with extra API request logging

RUN echo 'replace	github.com/filecoin-project/go-jsonrpc  => ../go-jsonrpc' >> go.mod

# Build Lotus

RUN make clean 2k

# Fetch params

RUN ./lotus fetch-params 2048
